import { describe, expect, it } from "vitest";
import type { Turn } from "../src/types.js";
import { renderMarkdown } from "../src/render/markdown.js";
import { renderHtml, markdownToHtml, escapeHtml } from "../src/render/html.js";

const meta = { title: "demo 会话片段", date: "2026-07-01" };
const inlinePng =
  "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9Z7VwAAAAASUVORK5CYII=";
const inlinePngWithParameter = inlinePng.replace(
  "data:image/png;",
  "data:image/png;charset=utf-8;",
);
const inlinePngWithEntity = inlinePng.replace("data:", "data&#x3A;");

const turns: Turn[] = [
  {
    index: 1,
    userText: '帮我看看 <script>alert("x")</script> 这段\n[图片]',
    userImages: [
      { mediaType: "image/png", dataUrl: "data:image/png;base64,QUJDRA==" },
    ],
    assistant: [
      { kind: "thinking", text: "先判断是不是 XSS 演示。" },
      {
        kind: "tool",
        text: "Bash: grep -r alert src",
        toolName: "Bash",
        toolInput: "command: grep -r alert src\ndescription: 找 alert 调用",
        toolPrimary: "grep -r alert src",
        toolResult: "src/x.ts: 1 处匹配",
      },
      {
        kind: "text",
        text: [
          "## 结论",
          "",
          "- 第一点",
          "- **第二点**",
          "",
          "1. 有序一",
          "2. 有序二",
          "",
          "装依赖用 `npm i`，文档见 [官网](https://example.com/a?b=1&c=2)。",
          "",
          "```js",
          "const ok = 1 < 2 && \"a\" !== 'b';",
          "```",
        ].join("\n"),
      },
    ],
    timestamp: "2026-07-01T10:00:01.000Z",
  },
  {
    index: 2,
    userText: "多行\n用户输入",
    assistant: [],
    timestamp: null,
  },
];

describe("renderMarkdown", () => {
  const md = renderMarkdown(turns, meta);

  it("标题、日期、页脚署名、轮次结构齐全", () => {
    expect(md).toContain("# demo 会话片段");
    expect(md).toContain("2026-07-01");
    expect(md).toContain("导出自本地会话 · Generated by airgap");
    expect(md).toContain("## 第 1 轮");
    expect(md).toContain("## 第 2 轮");
  });

  it("用户文本 blockquote 区隔，多行都带 > 前缀", () => {
    expect(md).toContain("> 多行");
    expect(md).toContain("> 用户输入");
  });

  it("AI 文本原样保留 markdown，thinking 进 blockquote，工具行折叠为列表项", () => {
    expect(md).toContain("## 结论");
    expect(md).toContain("- **第二点**");
    expect(md).toContain("> 💭 先判断是不是 XSS 演示。");
    expect(md).toContain("- 🔧 `Bash: grep -r alert src`");
  });

  it("tools=none 时工具行整体省略，文本/思考不受影响", () => {
    const none = renderMarkdown(turns, meta, { tools: "none" });
    expect(none).not.toContain("🔧");
    expect(none).not.toContain("grep -r alert src");
    expect(none).toContain("> 💭 先判断是不是 XSS 演示。");
    expect(none).toContain("## 结论");
  });

  it("不把图片二进制写进 Markdown 导出", () => {
    expect(md).toContain("[图片]");
    expect(md).not.toContain("data:image/");
    expect(md).not.toContain("QUJDRA==");
  });

  it("剥离文本字段里的内联图片字节", () => {
    const withInlineData: Turn = {
      index: 1,
      userText: `用户粘贴 ${inlinePng}`,
      assistant: [{ kind: "text", text: `![secret screenshot](${inlinePng})` }],
      timestamp: null,
    };
    const output = renderMarkdown([withInlineData], { title: `标题 ${inlinePng}`, date: meta.date });

    expect(output).not.toContain("data:image/");
    expect(output).not.toContain("iVBORw0KGgo");
    expect(output.match(/\[图片\]/g)).toHaveLength(3);
  });

  it.each([
    ["MIME 参数", inlinePngWithParameter],
    ["HTML 实体", inlinePngWithEntity],
  ])("剥离 Markdown 规范化后的%s图片字节", (_label, dataUrl) => {
    const withInlineData: Turn = {
      index: 1,
      userText: "hello",
      assistant: [{ kind: "text", text: `![secret screenshot](${dataUrl})` }],
      timestamp: null,
    };

    const output = renderMarkdown([withInlineData], meta);

    expect(output).toContain("[图片]");
    expect(output).not.toContain("iVBORw0KGgo");
  });
});

describe("renderHtml", () => {
  const html = renderHtml(turns, meta);

  it("Dossier 极简风要素：bone/paper/off-black/pastel tokens、深色媒体查询、页脚署名", () => {
    expect(html).toContain("prefers-color-scheme: dark");
    expect(html).toContain("--color-bone:");
    expect(html).toContain("--color-paper:");
    expect(html).toContain("--color-off-black:");
    expect(html).toContain("--pastel-green-fg:");
    expect(html).toContain("--font-serif");
    expect(html).toContain("--font-sans");
    // 旧 Monad/Evergreen 视觉残留必须清除
    expect(html).not.toContain("#95ec69");
    expect(html).not.toContain("--glass-bg");
    expect(html).not.toContain("backdrop-filter");
    expect(html).not.toContain("--color-linen-canvas");
    expect(html).not.toContain("--color-sage");
    // minimalist-ui 铁律：禁 Inter/Roboto 字体、HTML-UI 禁 emoji
    expect(html).not.toContain('"Inter"');
    expect(html).not.toContain("Roboto");
    expect(html).not.toContain("💭");
    expect(html).toContain('class="msg-user"');
    expect(html).toContain('class="msg-ai"');
    expect(html).toContain("导出自本地会话 · Generated by airgap");
    expect(html).toContain("—— 第 1 轮 ——");
  });

  it("用户文本先转义：script 标签不落地，换行转 <br>", () => {
    expect(html).toContain("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
    expect(html).not.toContain('<script>alert("x")');
    expect(html).toContain("多行<br>用户输入");
  });

  it("展示已解析的用户原图并隐藏对应占位符", () => {
    const imageTurn: Turn = {
      index: 1,
      userText: "查看截图\n[图片]",
      userDisplayText: "查看截图",
      userImages: [{ mediaType: "image/png", dataUrl: "data:image/png;base64,QUJDRA==" }],
      assistant: [],
      timestamp: null,
    };
    const imageHtml = renderHtml([imageTurn], meta);
    expect(imageHtml).toContain('class="user-attachment"');
    expect(imageHtml).toContain('src="data:image/png;base64,QUJDRA=="');
    expect(imageHtml).toContain("查看截图");
    expect(imageHtml).not.toContain("[图片]");
  });

  it("纯图片轮次不渲染空文本节点", () => {
    const imageHtml = renderHtml([{
      index: 1,
      userText: "[图片]",
      userDisplayText: "",
      userImages: [{ mediaType: "image/jpeg", dataUrl: "data:image/jpeg;base64,QUJDRA==" }],
      assistant: [],
      timestamp: null,
    }], meta);
    expect(imageHtml).toContain('class="user-attachments"');
    expect(imageHtml).not.toContain(">[图片]<");
    expect(imageHtml).not.toContain('class="user-text"');
  });

  it("保留用户亲自输入的图片标记，只隐藏解析器生成的占位符", () => {
    const imageHtml = renderHtml([{
      index: 1,
      userText: "[图片]\n这行是用户正文\n[图片]",
      userDisplayText: "[图片]\n这行是用户正文",
      userImages: [{ mediaType: "image/png", dataUrl: "data:image/png;base64,QUJDRA==" }],
      assistant: [],
      timestamp: null,
    }], meta);

    expect(imageHtml).toContain("[图片]<br>这行是用户正文");
    expect(imageHtml).toContain('class="user-attachment"');
  });

  it("渲染层拒绝手工注入的远程用户图片", () => {
    const imageHtml = renderHtml([{
      index: 1,
      userText: "[图片]",
      userImages: [{ mediaType: "image/png", dataUrl: "https://evil.example/private.png" }],
      assistant: [],
      timestamp: null,
    }], meta);
    expect(imageHtml).not.toContain("evil.example");
    expect(imageHtml).not.toContain('class="user-attachment"');
    expect(imageHtml).toContain("[图片]");
  });

  it("thinking 折叠进 details，工具默认渲染成一行摘要（summary 档）", () => {
    expect(html).toContain('<details class="thinking">');
    expect(html).toContain("先判断是不是 XSS 演示。");
    expect(html).toContain('<div class="toolline">');
    expect(html).toContain('<span class="tool-name">Bash</span>');
    expect(html).toContain('<span class="tool-brief">grep -r alert src</span>');
    expect(html).toContain('<span class="tool-status ok">✓</span>');
    // summary 档不出现完整卡：结构化 input（含 description 噪声）与结果区都不进导出物
    expect(html).not.toContain('<div class="toolcard');
    expect(html).not.toContain("找 alert 调用");
    expect(html).not.toContain("src/x.ts: 1 处匹配");
  });

  it("AI 文本走 markdown-it：标题/列表/粗体/行内码/链接/代码块", () => {
    expect(html).toContain("<h3>结论</h3>");
    expect(html).toContain("<li>第一点</li>");
    expect(html).toContain("<strong>第二点</strong>");
    expect(html).toContain("<ol>");
    expect(html).toContain("<li>有序一</li>");
    expect(html).toContain("<code>npm i</code>");
    expect(html).toContain('<a href="https://example.com/a?b=1&amp;c=2">官网</a>');
    // 代码块：< 与 & 转义、不泄漏（单引号 markdown-it 不转义，不断言）
    expect(html).toContain("const ok = 1 &lt; 2 &amp;&amp; &quot;a&quot;");
  });

  it("没有 assistant 块的轮不渲染空白 AI 卡片", () => {
    const tail = html.slice(html.indexOf("—— 第 2 轮 ——"));
    expect(tail).not.toContain('class="msg-ai"');
  });
});

describe("bilingual Share exports", () => {
  it("does not mutate transcript data while rendering either format", () => {
    const before = structuredClone(turns);
    renderHtml(turns, meta, { locale: "en" });
    renderMarkdown(turns, meta, { locale: "zh-CN" });
    expect(turns).toEqual(before);
  });

  it("renders English HTML chrome without changing transcript content", () => {
    const html = renderHtml(turns, meta, { locale: "en" });
    expect(html).toContain('<html lang="en">');
    expect(html).toContain("2 turns");
    expect(html).toContain("Turn 1");
    expect(html).toContain("Thinking");
    expect(html).toContain("Exported from a local session · Generated by airgap");
    expect(html).toContain("帮我看看");
    expect(html).toContain("先判断是不是 XSS 演示。");
  });

  it("renders English Markdown structure without changing transcript content", () => {
    const md = renderMarkdown(turns, meta, { locale: "en" });
    expect(md).toContain("2 turns");
    expect(md).toContain("## Turn 1");
    expect(md).toContain("**User**");
    expect(md).toContain("**AI**");
    expect(md).toContain("Thinking: 先判断是不是 XSS 演示。");
    expect(md).toContain("帮我看看");
  });
});

describe("工具展示三档与按工具类型的差异化渲染", () => {
  const toolTurns: Turn[] = [
    {
      index: 1,
      userText: "测试各类工具",
      assistant: [
        {
          kind: "tool",
          text: "Bash: npm test",
          toolName: "Bash",
          toolInput: "command: npm test\ndescription: 跑测试",
          toolPrimary: "npm test",
          toolResult: "146 passed",
        },
        {
          kind: "tool",
          text: "Read: /repo/src/scanner.ts",
          toolName: "Read",
          toolInput: "/repo/src/scanner.ts",
          toolPrimary: "/repo/src/scanner.ts",
          toolResult: "120 行",
        },
        {
          kind: "tool",
          text: "Edit: /repo/src/rules.ts",
          toolName: "Edit",
          toolInput: "file_path: /repo/src/rules.ts\nold_string: a\nnew_string: b",
          toolPrimary: "/repo/src/rules.ts",
          toolResult: "ok",
        },
        {
          kind: "tool",
          text: "mcp__db__query: select 1",
          toolName: "mcp__db__query",
          toolInput: "select 1",
          toolPrimary: "select 1",
          toolError: true,
        },
        { kind: "text", text: "跑完了。" },
      ],
      timestamp: null,
    },
  ];

  it("full：执行类渲成 $ 命令终端卡，参数噪声（description）不进导出物", () => {
    const full = renderHtml(toolTurns, meta, { tools: "full" });
    expect(full).toContain('<span class="cmd-prompt">$ </span>npm test');
    expect(full).toContain('<div class="toolcard-out">146 passed</div>');
    expect(full).not.toContain("跑测试");
  });

  it("full：检索类仍强制一行，不出 input/result 卡", () => {
    const full = renderHtml(toolTurns, meta, { tools: "full" });
    expect(full).toContain('<span class="tool-name">Read</span><span class="tool-brief">/repo/src/scanner.ts</span>');
    expect(full).not.toContain('<div class="toolcard-out">120 行</div>');
  });

  it("full：写改类头部突出文件名 basename；未知工具走通用卡；错误卡带 err 态", () => {
    const full = renderHtml(toolTurns, meta, { tools: "full" });
    expect(full).toContain('<span class="tool-file">rules.ts</span>');
    expect(full).toContain('<div class="toolcard-in">select 1</div>');
    expect(full).toContain('class="toolcard toolcard-err"');
    expect(full).toContain('<span class="tool-status err">✗ 失败</span>');
  });

  it("summary（默认档）：全部工具一行摘要，显式传参与缺省一致", () => {
    const byDefault = renderHtml(toolTurns, meta);
    const explicit = renderHtml(toolTurns, meta, { tools: "summary" });
    expect(byDefault).toBe(explicit);
    expect(byDefault).toContain('<span class="tool-name">Bash</span><span class="tool-brief">npm test</span>');
    expect(byDefault).toContain('<span class="tool-status err">✗</span>');
    expect(byDefault).not.toContain('<div class="toolcard');
  });

  it("none：工具痕迹在导出物里物理不存在（不是 CSS 藏起来），文本正常保留", () => {
    const none = renderHtml(toolTurns, meta, { tools: "none" });
    expect(none).not.toContain('<div class="toolline"');
    expect(none).not.toContain('<div class="toolcard');
    expect(none).not.toContain("npm test");
    expect(none).not.toContain("scanner.ts");
    expect(none).not.toContain("select 1");
    expect(none).toContain("跑完了。");
  });
});

describe("markdownToHtml（markdown-it）细节", () => {
  it("先转义再套格式：粗体里的 HTML 被转义", () => {
    expect(markdownToHtml("a **<b>** c").trim()).toBe("<p>a <strong>&lt;b&gt;</strong> c</p>");
  });

  it("行内码内容不再被二次格式化", () => {
    expect(markdownToHtml("`**not bold**`").trim()).toBe("<p><code>**not bold**</code></p>");
  });

  it("未闭合代码块容错收尾", () => {
    const html = markdownToHtml("```\nx = 1");
    expect(html).toContain("<pre>");
    expect(html).toContain("x = 1");
  });

  it("# 一级标题降级到 h2，### 及以下封顶 h4", () => {
    expect(markdownToHtml("# A").trim()).toBe("<h2>A</h2>");
    expect(markdownToHtml("#### B").trim()).toBe("<h4>B</h4>");
  });

  it("非 http(s) 链接不转 a 标签", () => {
    expect(markdownToHtml("[x](javascript:alert(1))")).not.toContain("<a ");
  });

  it("段内换行转 <br>，空行分段", () => {
    const html = markdownToHtml("a\nb\n\nc");
    expect(html).toContain("<br>");
    expect(html).toContain("<p>a");
    expect(html).toContain("b</p>");
    expect(html).toContain("<p>c</p>");
  });
});

describe("markdown-it 安全与零外链（渲染不可信会话内容）", () => {
  it("raw HTML 被转义，不产生活动标签", () => {
    const s = markdownToHtml("<script>alert(1)</script>");
    expect(s).not.toContain("<script>");
    expect(s).toContain("&lt;script&gt;");
    expect(markdownToHtml("<img src=x onerror=alert(1)>")).not.toContain("<img");
  });

  it("危险协议链接被丢弃", () => {
    expect(markdownToHtml("[c](javascript:alert(1))")).not.toContain("<a ");
    expect(markdownToHtml("[c](vbscript:msgbox(1))")).not.toContain("<a ");
    expect(markdownToHtml("[c](data:text/html,PHNjcmlwdD4=)")).not.toContain("<a ");
  });

  it("零外链：远程图被丢弃，仅支持的 base64 data:image 放行", () => {
    const remote = markdownToHtml("![x](https://evil.example/x.png)");
    expect(remote).not.toContain("<img");
    expect(remote).not.toContain("evil.example");
    const inline = markdownToHtml("![logo](data:image/png;base64,AAAA)");
    expect(inline).toContain("<img");
    expect(inline).toContain("data:image/png");
  });

  it("不渲染共享图片策略不认可的非 base64 data:image", () => {
    const html = markdownToHtml("![x](data:image/png;,%89PNG)");
    expect(html).not.toContain("<img");
  });
});

describe("markdown-it GFM 覆盖（手写版缺失的语法）", () => {
  it("表格", () => {
    const html = markdownToHtml("| A | B |\n| --- | --- |\n| 1 | 2 |");
    expect(html).toContain("<table>");
    expect(html).toContain("<th>A</th>");
    expect(html).toContain("<td>1</td>");
  });

  it("删除线 / 斜体 / 引用 / 水平线", () => {
    expect(markdownToHtml("~~x~~")).toContain("<s>x</s>");
    expect(markdownToHtml("*x*")).toContain("<em>x</em>");
    expect(markdownToHtml("> q")).toContain("<blockquote>");
    expect(markdownToHtml("---")).toContain("<hr>");
  });

  it("任务列表渲染成 disabled checkbox", () => {
    const html = markdownToHtml("- [ ] 待办\n- [x] 完成");
    expect(html).toContain('type="checkbox"');
    expect(html).toContain('checked="checked"');
    expect(html).toContain("disabled");
  });

  it("嵌套列表", () => {
    const html = markdownToHtml("- 顶层\n  - 嵌套");
    expect(html).toContain("<li>顶层");
    expect((html.match(/<ul>/g) ?? []).length).toBeGreaterThanOrEqual(2);
  });
});

describe("escapeHtml", () => {
  it("五个危险字符全转义", () => {
    expect(escapeHtml(`&<>"'`)).toBe("&amp;&lt;&gt;&quot;&#39;");
  });
});
