import { describe, expect, it } from "vitest";
import type { Turn } from "../src/types.js";
import { renderMarkdown } from "../src/render/markdown.js";
import { renderHtml, markdownToHtml, escapeHtml } from "../src/render/html.js";

const meta = { title: "demo 会话片段", date: "2026-07-01" };

const turns: Turn[] = [
  {
    index: 1,
    userText: '帮我看看 <script>alert("x")</script> 这段',
    assistant: [
      { kind: "thinking", text: "先判断是不是 XSS 演示。" },
      { kind: "tool", text: 'Bash: {"command":"grep -r alert src"}' },
      {
        kind: "text",
        text: [
          "## 结论",
          "",
          "- 第一点",
          "- **第二点**",
          "",
          "1. 有序一",
          "2. 有序二",
          "",
          "装依赖用 `npm i`，文档见 [官网](https://example.com/a?b=1&c=2)。",
          "",
          "```js",
          "const ok = 1 < 2 && \"a\" !== 'b';",
          "```",
        ].join("\n"),
      },
    ],
    timestamp: "2026-07-01T10:00:01.000Z",
  },
  {
    index: 2,
    userText: "多行\n用户输入",
    assistant: [],
    timestamp: null,
  },
];

describe("renderMarkdown", () => {
  const md = renderMarkdown(turns, meta);

  it("标题、日期、页脚署名、轮次结构齐全", () => {
    expect(md).toContain("# demo 会话片段");
    expect(md).toContain("2026-07-01");
    expect(md).toContain("导出自本地会话 · Generated by airgap");
    expect(md).toContain("## 第 1 轮");
    expect(md).toContain("## 第 2 轮");
  });

  it("用户文本 blockquote 区隔，多行都带 > 前缀", () => {
    expect(md).toContain("> 多行");
    expect(md).toContain("> 用户输入");
  });

  it("AI 文本原样保留 markdown，thinking 进 blockquote，工具行折叠为列表项", () => {
    expect(md).toContain("## 结论");
    expect(md).toContain("- **第二点**");
    expect(md).toContain("> 💭 先判断是不是 XSS 演示。");
    expect(md).toContain('- 🔧 `Bash: {"command":"grep -r alert src"}`');
  });
});

describe("renderHtml", () => {
  const html = renderHtml(turns, meta);

  it("微信聊天风要素：绿气泡色值、白卡片、页脚署名", () => {
    expect(html).toContain("#95ec69");
    expect(html).toContain('class="msg-user"');
    expect(html).toContain('class="msg-ai"');
    expect(html).toContain("导出自本地会话 · Generated by airgap");
    expect(html).toContain("—— 第 1 轮 ——");
  });

  it("用户文本先转义：script 标签不落地，换行转 <br>", () => {
    expect(html).toContain("&lt;script&gt;alert(&quot;x&quot;)&lt;/script&gt;");
    expect(html).not.toContain('<script>alert("x")');
    expect(html).toContain("多行<br>用户输入");
  });

  it("thinking 折叠进 details，工具行灰色斜体样式类", () => {
    expect(html).toContain('<details class="thinking">');
    expect(html).toContain("先判断是不是 XSS 演示。");
    expect(html).toContain('<div class="tool">🔧 Bash: {&quot;command&quot;:&quot;grep -r alert src&quot;}</div>');
  });

  it("AI 文本走轻量 markdown：标题/列表/粗体/行内码/链接/代码块", () => {
    expect(html).toContain("<h3>结论</h3>");
    expect(html).toContain("<li>第一点</li>");
    expect(html).toContain("<strong>第二点</strong>");
    expect(html).toContain("<ol><li>有序一</li><li>有序二</li></ol>");
    expect(html).toContain("<code>npm i</code>");
    expect(html).toContain('<a href="https://example.com/a?b=1&amp;c=2">官网</a>');
    expect(html).toContain("<pre><code>const ok = 1 &lt; 2 &amp;&amp; &quot;a&quot; !== &#39;b&#39;;</code></pre>");
  });

  it("没有 assistant 块的轮不渲染空白 AI 卡片", () => {
    const tail = html.slice(html.indexOf("—— 第 2 轮 ——"));
    expect(tail).not.toContain('class="msg-ai"');
  });
});

describe("markdownToHtml 细节", () => {
  it("先转义再套格式：粗体里的 HTML 被转义", () => {
    expect(markdownToHtml("a **<b>** c")).toBe("<p>a <strong>&lt;b&gt;</strong> c</p>");
  });

  it("行内码内容不再被二次格式化", () => {
    expect(markdownToHtml("`**not bold**`")).toBe("<p><code>**not bold**</code></p>");
  });

  it("未闭合代码块容错收尾", () => {
    expect(markdownToHtml("```\nx = 1")).toBe("<pre><code>x = 1</code></pre>");
  });

  it("# 一级标题映射到 h2，### 及以下封顶 h4", () => {
    expect(markdownToHtml("# A")).toBe("<h2>A</h2>");
    expect(markdownToHtml("#### B")).toBe("<h4>B</h4>");
  });

  it("非 http(s) 链接不转 a 标签", () => {
    expect(markdownToHtml("[x](javascript:alert(1))")).not.toContain("<a ");
  });

  it("段内换行转 <br>，空行分段", () => {
    expect(markdownToHtml("a\nb\n\nc")).toBe("<p>a<br>b</p>\n<p>c</p>");
  });
});

describe("escapeHtml", () => {
  it("五个危险字符全转义", () => {
    expect(escapeHtml(`&<>"'`)).toBe("&amp;&lt;&gt;&quot;&#39;");
  });
});
