import type { Turn } from "../types.js";

function blockquote(s: string): string {
  return s
    .split("\n")
    .map((line) => (line.trim().length > 0 ? `> ${line}` : ">"))
    .join("\n");
}

/**
 * 干净 markdown 输出：AI 文本原样保留（本身就是 markdown），
 * 用户文本用 blockquote 区隔，thinking 折叠进 blockquote，工具行折叠成列表项。
 */
export function renderMarkdown(turns: Turn[], meta: { title: string; date: string }): string {
  const out: string[] = [];
  out.push(`# ${meta.title}`);
  out.push("");
  out.push(`> ${meta.date} · 共 ${turns.length} 轮 · 导出自本地会话 · Generated by airgap`);
  out.push("");
  for (const turn of turns) {
    out.push(`## 第 ${turn.index} 轮`);
    out.push("");
    out.push("**🧑 用户**");
    out.push("");
    out.push(blockquote(turn.userText));
    out.push("");
    if (turn.assistant.length > 0) {
      out.push("**🤖 AI**");
      out.push("");
      for (const block of turn.assistant) {
        if (block.kind === "text") {
          out.push(block.text.trim());
        } else if (block.kind === "thinking") {
          out.push(blockquote(`💭 ${block.text.trim()}`));
        } else {
          out.push(`- 🔧 \`${block.text.replace(/`/g, "'")}\``);
        }
        out.push("");
      }
    }
  }
  return `${out.join("\n").trimEnd()}\n`;
}
